[#17] 게시물 조회
f-lab-edu/sns-itda pull request #18
Opened 2020-09-14 15:23 UTC by cyj199637

- 게시물 조회 기능 구현
- Image 객체를 다루던 기능이나 Sql을 각각 FileService, FileMapper로 분리

2020-09-17 10:04 UTC, f-lab-dev approved these changes

2020-09-21 12:20 UTC, f-lab-dev requested changes
여기서는 피드를 조회할 때 더 성능을 높힐 수 있는 방법이 있을 것 같습니다~
어떤 방법이 있을까요?

2020-09-21 15:12 UTC, cyj199637 commented
혹시 성능을 높이는 방법이 cashing을 적용하는 것일까요??
만약 그렇다면 게시물과 관련된 로직을 마무리 한 다음에 따로 이슈를 만들어서 하려고 했는데
이 이슈에 같이 하는 것이 나은가요?

2020-09-26 07:13 UTC, f-lab-dev commented on src/main/resources/mapper/PostMapper.xml
> +        LEFT OUTER JOIN image as i ON i.postId = p.id
여기서 OUTER JOIN을 써주신 이유가 있으실까요?

2020-09-26 12:35 UTC, cyj199637 commented on src/main/resources/mapper/PostMapper.xml
> +        LEFT OUTER JOIN image as i ON i.postId = p.id
image가 없는 post도 있어서 OUTER JOIN으로 처리했습니다!

2020-09-27 14:54 UTC, f-lab-dev commented on src/main/resources/mapper/PostMapper.xml
> +        LEFT OUTER JOIN image as i ON i.postId = p.id
아 만약 인스타그램 같은 SNS라면 무조건 이미지가 있어야겠지만 여기선 도메인 규칙상 아닌가보군요~

2020-09-27 14:54 UTC, f-lab-dev approved these changes

2020-10-10 09:03 UTC, merged