[#49] Docker로 배포하기
f-lab-edu/sns-itda pull request #50
Opened 2020-12-06 16:45 UTC by cyj199637

2020-12-08 02:49 UTC, f-lab-dev commented on Dockerfile
> +COPY target/sns-server-0.0.1-SNAPSHOT.jar sns-itda.jar
만약 `pom.xml`에서 릴리즈마다 버전이 계속 바뀐다면 이 파일이름도 계속 달라지니 배포에 실패하지 않을까요?

2020-12-08 02:49 UTC, f-lab-dev commented on Dockerfile
> +VOLUME /tmp
volume을 넣어주신 이유가 있으실까요?

2020-12-08 02:49 UTC, f-lab-dev commented on Dockerfile
> +ENTRYPOINT ["java", "-jar", "/sns-itda.jar", "-Dspring.profiles.active=prod"]
`"-Dspring.profiles.active=prod"` 같은 config값은 외부에서 주입받는게 좋지 않을까요?

2020-12-10 13:48 UTC, f-lab-dev commented on Dockerfile
> +ENTRYPOINT ["java", "-jar", "/sns-itda.jar", "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}"]
JVM argument를 유동적으로 조절하기 위해 jvm 옵션을 통째로 주입할 수 있게 만들어줘도 좋을 것 같네요~

2020-12-13 14:51 UTC, f-lab-dev approved these changes

2020-12-13 14:52 UTC, f-lab-dev requested changes

2020-12-13 14:52 UTC, f-lab-dev commented on Dockerfile
> +ENTRYPOINT ["java", "-jar", "/sns-itda.jar"]
여기 JVM argument 넣는곳이 없는데 그러면 argument는 어떻게 받는걸까요?

2020-12-13 17:00 UTC, cyj199637 commented on Dockerfile
> +ENTRYPOINT ["java", "-jar", "/sns-itda.jar"]
환경 변수들을 작성한 env 파일을 따로 작성하여 배포 서버에서 컨테이너를 생성할 때
해당 파일을 사용하도록 명령어를 작성했습니다!

2020-12-14 03:32 UTC, f-lab-dev commented on Dockerfile
> +ENTRYPOINT ["java", "-jar", "/sns-itda.jar"]
환경변수가 자동으로 jvm argument로 주입되는걸까요? 예를 들면 힙사이즈 같은 설정도요~

2020-12-18 16:17 UTC, cyj199637 commented on Dockerfile
> +ENTRYPOINT ["java", "-jar", "/sns-itda.jar"]
테스트해보니 JVM 관련 설정들은 적용되지 않네요...다시 수정하겠습니다!

2020-12-19 02:50 UTC, f-lab-dev approved these changes

2021-01-07 06:29 UTC, merged